### ISSUE TITLE
"goa update-goa" fails with bwrap enabled

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/goa#136]
I tested on some older state and current master (with Ubuntu 24.04 and @alex-ab workaround for apparmor).

```
> goa update-goa 
[goa-utils.git] Error: Command 'file normalize /<some path>/goa.git/share/goa/../..' operates on an invalid path. Valid paths are:
 
 /<some path>/goa-utils.git 

 You may consider setting 'allowed_paths' in your $HOME/goarc or /goarc file.

> goa --version
master

> pwd
/<some path>/goa-utils.git

> ls -d1 /<some path>/goa*
goa-utils.git/
goa.git/

> (cd /<some path>/goa.git; goa update-goa)
No user exists for uid 1000
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[goa.git] Error: Goa update could not fetch new version:
child process exited abnormally

> id -u
1000
```

**Comment by jschlatow** [comment]
@chelmuth I just pushed two commits that fix the allowed_paths error and enable the use with DISABLE_SANDBOX. I'm still trying to figure out how to convince git to execute in bwrap, though.

**Comment by chelmuth** [comment]
```
> goa --version 
invalid command name "unsafe_file"
    while executing
"unsafe_file normalize [file join $tool_dir .. ..]"
    (procedure "goa_git" line 3)
    invoked from within
"goa_git  rev-parse --abbrev-ref HEAD"
    (procedure "current_goa_branch" line 3)
    invoked from within
"current_goa_branch"
    (file "<some path>/goa.git/share/goa/lib/command_line.tcl" line 29)
    invoked from within
"source [file join $tool_dir lib command_line.tcl]"
```

**Comment by jschlatow** [comment]
For the record, in order to update Goa with a broken `goa update-goa`, the following commands executed in the Goa repository should get it working (once the commits have entered the master branch):

```
$ git fetch origin
$ git checkout origin/master
```

**Comment by chelmuth** [comment]
I forced origin/staging in goa.git but still get the following (bwrap disabled).

```
> export DISABLE_SANDBOX=1; goa versions
[goa-utils.git] Error: In /<some path>/goa-utils.git/goarc: 
 Path variable 'depot_dir' set to '/<some path>/genode_sculpt.git/depot'
 defines an invalid path. Valid paths are:

 /<some path>/goa-utils.git 

 You may consider setting 'allowed_paths' in your $HOME/goarc or /goarc file.
```

As *<some path\>* is not a subdirectory of */home* I had to put *goarc* under */*. Any objections to always parse *$HOME/goarc*?

**Comment by chelmuth** [comment]
> Note that the allowed_paths mechanism is independent of sandboxing. The former is for safe-guarding file operations made by Goa itself whereas the latter is to constrain sub-processes.

Thanks for clearing up my misunderstanding! With #137 applied, I can now successfully run all desired goa commands under *<some path\>*.
